
version: '3'
services:
  web:
    image: sorry:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEBIAN_REPO: ${DEBIAN_REPO:-mirrors.aliyun.com}
        PIP_INDEX_URL: ${PIP_INDEX_URL:-https://pypi.tuna.tsinghua.edu.cn/simple}
    ports:
     - "15000:15000"
            